parameters:
#    futjikato_phpodcast.example.class: Futjikato\PhpodcastBundle\Example

services:
#    futjikato_phpodcast.example:
#        class: %futjikato_phpodcast.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
