parameters:
#    futjikato_admin.example.class: Futjikato\AdminBundle\Example

services:
#    futjikato_admin.example:
#        class: %futjikato_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
